using System.Globalization;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;

namespace Docuconf.Contract;

/// <summary>Writes a <see cref="ContractModel"/> as a <c>contract.cue</c> document (SPEC §4).</summary>
public static partial class CueWriter
{
    private static readonly JsonSerializerOptions Json = new() { Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping };

    [GeneratedRegex("^[A-Za-z_][A-Za-z0-9_]*$")]
    private static partial Regex Identifier();

    /// <summary>Generator details recorded in the contract's metadata.</summary>
    public sealed record Generator(string Sdk, string Version);

    /// <summary>Writes the contract. Output is deterministic for a given model.</summary>
    public static string Write(ContractModel model, Generator generator, string? appVersion = null) =>
        Build(model, generator, appVersion).ToString();

    /// <summary>
    /// Writes the contract as JSON, the form <c>cue export contract.cue --out json</c> gives and
    /// <see cref="DocuconfContract.FromJson"/> reads, without needing a CUE module.
    /// </summary>
    public static string WriteJson(ContractModel model, Generator generator, string? appVersion = null) =>
        Build(model, generator, appVersion).Json.ToJsonString(new JsonSerializerOptions { WriteIndented = true, Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping }) + "\n";

    private static Writer Build(ContractModel model, Generator generator, string? appVersion)
    {
        var w = new Writer();
        w.Line("// Code generated by docuconf. DO NOT EDIT.");
        w.Line($"package {model.Service.Replace('-', '_')}");
        w.Line();
        w.Line("import \"docuconf.dev/contract\"");
        w.Line();
        w.Open(null);
        w.Field("apiVersion", Str("docuconf.dev/v1alpha1"));
        w.Field("kind", Str("ConfigContract"));
        w.Open("metadata");
        w.Field("name", Str(model.Service));
        if (appVersion is not null)
        {
            w.Field("appVersion", Str(appVersion));
        }

        w.Field("generator", $"{{\"language\": \"dotnet\", \"sdk\": {Str(generator.Sdk)}, \"version\": {Str(generator.Version)}}}", $"{{language: \"dotnet\", sdk: {Str(generator.Sdk)}, version: {Str(generator.Version)}}}");
        w.Close();

        w.Open("vars");
        foreach (var spec in model.Vars.Values)
        {
            WriteVar(w, spec);
        }

        w.Close();

        if (model.Files.Count > 0)
        {
            w.Open("files");
            foreach (var spec in model.Files.Values)
            {
                WriteFile(w, spec);
            }

            w.Close();
        }

        if (model.Overlays.Count > 0)
        {
            w.Open("overlays");
            foreach (var o in model.Overlays.Values)
            {
                w.Open(o.Name);
                if (o.Description is not null)
                {
                    w.Field("description", Str(o.Description));
                }

                w.Field("format", Str("json"));
                w.Field("path", Str(o.Path));
                w.Field("keySeparator", Str(":"));
                w.Field("reload", Str(o.ReloadOnChange ? "watch" : "restart"));
                w.Close();
            }

            w.Close();
        }

        if (model.Profiles is { } profiles)
        {
            w.Open("profiles");
            w.Field("selector", Str(profiles.Selector));
            w.Field("default", Str(profiles.Default));
            w.Open("defaults");
            foreach (var (environment, values) in profiles.Defaults)
            {
                w.Open(environment);
                foreach (var (name, value) in values)
                {
                    w.Field(name, Value(value));
                }

                w.Close();
            }

            w.Close();
            w.Close();
        }

        w.Close();
        return w;
    }

    private static void WriteVar(Writer w, VarSpec v)
    {
        w.Open(v.Name);
        w.Field("type", Str(v.Type switch
        {
            VarType.String => "string",
            VarType.Int => "int",
            VarType.Float => "float",
            VarType.Bool => "bool",
            VarType.Duration => "duration",
            VarType.Url => "url",
            VarType.Enum => "enum",
            VarType.Json => "json",
            _ => "list",
        }));
        w.Field("description", Str(v.Description));
        if (v.Required) w.Field("required", "true");
        if (v.Secret) w.Field("secret", "true");
        if (v.ConfigKey.Length > 0) w.Field("configKey", Str(v.ConfigKey));
        // The .NET configuration binder reads TimeSpan as hh:mm:ss and lists from indexed keys (NAME__0, NAME__1).
        if (v.Type == VarType.Duration) w.Field("encoding", Str(v.Encoding ?? "timespan"));
        if (v.Type == VarType.List)
        {
            w.Field("items", Str(v.Items!));
            w.Field("encoding", Str(v.Encoding ?? "indexed"));
            if (v.Separator is { } separator) w.Field("separator", Str(separator));
        }

        if (v.Values is { } values) w.Field("values", List(values.Select(Str)));
        if (v.Schemes is { } schemes) w.Field("schemes", List(schemes.Select(Str)));
        if (v.Min is not null) w.Field("min", Value(v.Min));
        if (v.Max is not null) w.Field("max", Value(v.Max));
        if (v.MinLength is { } minLength) w.Field("minLength", Num(minLength));
        if (v.MaxLength is { } maxLength) w.Field("maxLength", Num(maxLength));
        if (v.Pattern is { } pattern) w.Field("pattern", Str(pattern));
        if (v.MinItems is { } minItems) w.Field("minItems", Num(minItems));
        if (v.MaxItems is { } maxItems) w.Field("maxItems", Num(maxItems));
        if (v.ItemMin is { } itemMin) w.Field("itemMin", Num(itemMin));
        if (v.ItemMax is { } itemMax) w.Field("itemMax", Num(itemMax));
        if (v.ItemMinLength is { } itemMinLength) w.Field("itemMinLength", Num(itemMinLength));
        if (v.ItemMaxLength is { } itemMaxLength) w.Field("itemMaxLength", Num(itemMaxLength));
        if (v.Schema is { } schema) w.Field("schema", Schema(schema, w.Depth));
        if (v.Default is { } value) w.Field("default", Value(value, v.Type == VarType.Float));
        w.Close();
    }

    private static void WriteFile(Writer w, FileSpec f)
    {
        w.Open(f.Name);
        w.Field("type", Str(f.Type switch
        {
            FileType.Config => "config",
            FileType.Tls => "tls",
            FileType.CaBundle => "caBundle",
            FileType.Keystore => "keystore",
            FileType.Text => "text",
            _ => "binary",
        }));
        if (f.Format is { } format) w.Field("format", Str(format));
        w.Field("description", Str(f.Description));
        if (f.Required) w.Field("required", "true");
        if (f.Secret && f.Type is not (FileType.Tls or FileType.Keystore)) w.Field("secret", "true");
        w.Field("path", Str(f.Path));
        if (f.PathEnv is { } pathEnv) w.Field("pathEnv", Str(pathEnv));
        if (f.Reload == Reload.Watch) w.Field("reload", Str("watch"));
        if (f.MaxSize is { } maxSize) w.Field("maxSize", Num(maxSize));
        if (f.DnsNames is { } dnsNames) w.Field("dnsNames", List(dnsNames.Select(Str)));
        if (f.KeyAlgorithms is { } algorithms) w.Field("keyAlgorithms", List(algorithms.Select(Str)));
        if (f.MinRemaining is { } minRemaining) w.Field("minRemaining", Str(minRemaining));
        if (f.RequireCA) w.Field("requireCA", "true");
        if (f.MinCertificates is { } minCertificates) w.Field("minCertificates", Num(minCertificates));
        if (f.PasswordVar is { } passwordVar) w.Field("passwordVar", Str(passwordVar));
        if (f.Pattern is { } pattern) w.Field("pattern", Str(pattern));
        if (f.MinLength is { } minLength) w.Field("minLength", Num(minLength));
        if (f.MaxLength is { } maxLength) w.Field("maxLength", Num(maxLength));
        if (f.Schema is { } schema) w.Field("schema", Schema(schema, w.Depth));
        w.Close();
    }

    private static string Value(object value, bool asFloat = false) => value switch
    {
        string s => Str(s),
        bool b => b ? "true" : "false",
        long l when asFloat => l.ToString(CultureInfo.InvariantCulture) + ".0",
        long l => l.ToString(CultureInfo.InvariantCulture),
        int i => i.ToString(CultureInfo.InvariantCulture),
        double d => FloatLiteral(d),
        List<object> items => List(items.Select(i => Value(i))),
        JsonNode node => node.ToJsonString(Json), // JSON is valid CUE.
        _ => throw new ArgumentException($"Cannot write {value.GetType().Name} into a contract."),
    };

    private static string FloatLiteral(double d)
    {
        var s = d.ToString("R", CultureInfo.InvariantCulture);
        return s.Contains('.', StringComparison.Ordinal) || s.Contains('E', StringComparison.Ordinal) ? s : s + ".0";
    }

    private static string Str(string s) => JsonSerializer.Serialize(s, Json);

    private static string Num(long n) => n.ToString(CultureInfo.InvariantCulture);

    private static string List(IEnumerable<string> items) => "[" + string.Join(", ", items) + "]";

    private static string Label(string name) => Identifier().IsMatch(name) ? name : Str(name);

    // JSON is valid CUE, so a schema is written as indented JSON.
    private static string Schema(JsonNode schema, int depth)
    {
        var json = schema.ToJsonString(new JsonSerializerOptions { WriteIndented = true, Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping });
        var indent = new string('\t', depth);
        return string.Join("\n" + indent, json.Split('\n').Select(l => ReindentJson(l)));
    }

    private static string ReindentJson(string line)
    {
        int spaces = line.TakeWhile(c => c == ' ').Count();
        return new string('\t', spaces / 2) + line[spaces..];
    }

    /// <summary>Writes CUE lines and builds the same document as JSON. Field values are JSON literals.</summary>
    private sealed class Writer
    {
        private readonly StringBuilder _sb = new();
        private readonly Stack<JsonObject> _objects = new();

        public JsonObject Json { get; } = new();

        public int Depth { get; private set; }

        public void Line(string text = "")
        {
            if (text.Length > 0)
            {
                _sb.Append('\t', Depth);
            }

            _sb.Append(text).Append('\n');
        }

        /// <summary>Opens an object field, or the contract itself when <paramref name="label"/> is null.</summary>
        public void Open(string? label)
        {
            if (label is null)
            {
                Line("contract.#Contract & {");
                _objects.Push(Json);
            }
            else
            {
                Line($"{Label(label)}: {{");
                var child = new JsonObject();
                _objects.Peek()[label] = child;
                _objects.Push(child);
            }

            Depth++;
        }

        public void Close()
        {
            Depth--;
            Line("}");
            _objects.Pop();
        }

        /// <summary>A field whose value is a JSON literal, written as <paramref name="cue"/> in CUE when given.</summary>
        public void Field(string name, string json, string? cue = null)
        {
            Line($"{Label(name)}: {cue ?? json}");
            _objects.Peek()[name] = JsonNode.Parse(json);
        }

        public override string ToString() => _sb.ToString();
    }
}
