// Code generated by docuconf. DO NOT EDIT.
package gateway

import "docuconf.dev/contract"

contract.#Contract & {
	apiVersion: "docuconf.dev/v1alpha1"
	kind: "ConfigContract"
	metadata: {
		name: "gateway"
		generator: {language: "dotnet", sdk: "Docuconf.Options", version: "0.1.0-test"}
	}
	vars: {
		DOTNET_ENVIRONMENT: {
			type: "string"
			description: "Hosting environment; selects appsettings.{Environment}.json"
			default: "Production"
		}
		GATEWAY__BROKERS: {
			type: "list"
			description: "Kafka brokers to connect to"
			configKey: "Gateway:Brokers"
			items: "string"
			encoding: "indexed"
			minItems: 1
			default: ["kafka-0:9092", "kafka-1:9092"]
		}
		GATEWAY__DATABASEURL: {
			type: "url"
			description: "Database connection string"
			required: true
			secret: true
			configKey: "Gateway:DatabaseUrl"
			schemes: ["postgres"]
		}
		GATEWAY__KEYSTOREPASSWORD: {
			type: "string"
			description: "Password for the partner keystore"
			required: true
			secret: true
			configKey: "Gateway:KeystorePassword"
		}
		GATEWAY__PORT: {
			type: "int"
			description: "HTTP listen port"
			configKey: "Gateway:Port"
			min: 1
			max: 65535
			default: 9000
		}
		GATEWAY__TIMEOUT: {
			type: "duration"
			description: "Upstream request timeout"
			configKey: "Gateway:Timeout"
			encoding: "timespan"
			min: "1s"
			max: "5m"
			default: "30s"
		}
		GATEWAY__TRACING: {
			type: "bool"
			description: "Whether to trace requests"
			configKey: "Gateway:Tracing"
			default: true
		}
	}
	files: {
		license: {
			type: "text"
			description: "Licence key"
			required: true
			path: "/etc/gw/license/license.key"
			pattern: "^[A-Z]{4}\\n?$"
		}
		partner: {
			type: "keystore"
			format: "pkcs12"
			description: "Client certificate for the partner API"
			path: "/etc/gw/partner/keystore.p12"
			passwordVar: "GATEWAY__KEYSTOREPASSWORD"
		}
		routes: {
			type: "config"
			format: "json"
			description: "Routing table"
			required: true
			path: "/etc/gw/routes/routes.json"
			maxSize: 65536
			schema: {
				"type": "object",
				"properties": {
					"items": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"match": {
									"type": "string",
									"description": "Path prefix to match",
									"pattern": "^(?:/.*)$"
								},
								"upstream": {
									"type": "string",
									"description": "Upstream URL"
								}
							},
							"additionalProperties": false,
							"required": [
								"match",
								"upstream"
							]
						},
						"description": "Routes, matched in order",
						"minItems": 1
					}
				},
				"additionalProperties": false,
				"required": [
					"items"
				]
			}
		}
		tls: {
			type: "tls"
			description: "Serving certificate"
			required: true
			path: "/etc/gw/tls"
			reload: "watch"
			dnsNames: ["gw.internal"]
			minRemaining: "720h"
			requireCA: true
		}
		"trusted-cas": {
			type: "caBundle"
			description: "Private CAs to trust"
			path: "/etc/gw/ca/bundle.pem"
			pathEnv: "SSL_CERT_FILE"
		}
	}
	profiles: {
		selector: "DOTNET_ENVIRONMENT"
		default: "Production"
		defaults: {
			Production: {
				GATEWAY__TRACING: false
			}
		}
	}
}
